### ISSUE TITLE
Update Documentation and Reference Implementation to Reflect DD 2.1 Field Names

### ISSUE THREAD

**Issue by darnjo** [RESOStandards/reso-upi-v2#21]
Update the UPI-related field names to the following for DD 2.1, based on July DD meeting.

Formula is:

```
urn:reso:upi:<Version>:<Country>:<CountrySubdivision>:<ParcelNumber>[:sub:<ParcelSubcomponent>]
```

where:
* `Version` is the major and minor version in the format `Major.Minor` (following [Semver](https://semver.org/)). Current version is `2.0`.
* `UniversalParcelId` is the [ParcelNumber](https://ddwiki.reso.org/display/DDW20/ParcelNumber+Field) used to populate that portion of the UPI v2+ specification. 
* `Country` is the [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) country code. Example: `US`.
* `CountrySubdivision` is a country-specific formula used to describe the location of the county (and sometimes subcounty) within a given country where the parcel is located. In the U.S., [GEOID](https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html) is used. 
* `ParcelNumber` is the assessor's parcel number assigned by the local authority, following the Data Dictionary definition. With the UPI v2 construction, special characters are encoded into the ParcelNumber as-is, and can be removed when trying to use for deduplication. URNs are a kind of URI, and special characters between the colon separators should be percent-encoded when used with a transport like HTTP. [See URN Wikipedia](https://en.wikipedia.org/wiki/Uniform_Resource_Name) or [RFC 8141](https://datatracker.ietf.org/doc/html/rfc8141#section-4.4).
* `ParcelSubcomponent` is a optional identifier that can be used to assign subcomponents of the property to things like air rights, boat docks, and parking spots if they aren't assigned by a local authority. This was previously referred to as `SubparcelNumber` but the name was changed to clarify that it doesn't have any connection to the `ParcelNumber` component. 

cc: @sdebord @mlesswing

**Comment by gsaxRESO** [comment]
I had a question about using `UniversalParcelId` with lowercase "Id" vs. the **[Microsoft-suggested PascalCase guidelines for 2-digit acronyms](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions)**, which says it should be "ID," thus `UniversalParcelID`.

We recently changed some "Id" items to "ID" in the Data Dictionary Workgroup:

**[Changing "Id" to "ID" for DD 2.0 Items](https://reso.atlassian.net/wiki/x/AQBaKAI)**
The Data Dictionary Workgroup discussed retroactively changing the names of four **Media Resource** field additions to use "ID" instead of "Id." The reason for the proposed change was to maintain consistency with other OriginatingSystemID and ResourceRecordID fields across the Data Dictionary, which all use "ID."

It is known that the Data Dictionary uses both forms at this time, and the group is discussing long-term goals around assuring that two-letter acronyms and abbreviations are consistently in uppercase letters to align with wider PascalCase norms.

Specific fields proposed to be changed:

- OriginatingSystemResourceRecordId
- SourceSystemResourceRecordId
- OriginatingSystemResourceRecordSystemId
- SourceSystemResourceRecordSystemId

The motion to retroactively adjust the above field names to end with "ID" instead of "Id" passed.

Is this a different situation? Like are we trying to now be consistent with other nearby fields that use "Id" and do we plan to take  a situational approach to each new addition vs. committing to one style?

**Comment by darnjo** [comment]
We can definitely use ID vs Id if that's what the convention is. Would be nice to find that documented from an additional source as well. I can look a bit myself.

Just need to be consistent one way or another.

**Comment by gsaxRESO** [comment]
The **[other source](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2019/code-quality/ca1709?view=vs-2019-archive&viewFallbackFrom=vs-2022)** I have is also Microsoft-based. I kind of limited my scope to MS because of our adherence to OData, but I can look deeper, too.

For the longest time, I thought that we were supposed to do 2-digit acronyms as we should any other PascalCase acronym (e.g., Aor, Mls, Upi, Gps), but I honestly don't know at this point. I remember u/BradleyUffner **[throwing me for a loop on Reddit](https://www.reddit.com/r/csharp/comments/ge0yo5/is_it_still_recommended_to_pascalcase_acronyms/?rdt=60582)** with this:

> "Id" isn't an acronym though, it's an abbreviation, which is why the "d" should be lower case according to the standard. If it was an acronym, both letters would be capitalized, since the standard says to capitalize both letters of a 2-letter acronym.

**[This StackOverflow item](https://stackoverflow.com/questions/12369539/how-to-use-pascal-casing-and-camel-casing-for-short-acronyms-in-c)** from 2012 addresses the same thing with a comment from someone who notes that Microsoft disagrees with his take:

> I wouldn't capitalise "ID" regardless of convention because it's an abbreviation, not an acronym, but Microsoft disagrees with me in all its examples. – millimoose, Sep 11, 2012

It's a tricky guideline by Microsoft, and it doesn't look like everyone agrees with them, so no wonder we bounce back and forth between usage in the DD. If consistency is king, we have our work cut out for us, because we don't always follow Microsoft guidance for 3+-digit acronyms in the DD either, haha.

If there ever comes a day when we try to make our PascalCase more consistent, if that's even possible, all discrepancies are documented.

**Comment by darnjo** [comment]
There are automated tools that validate PascalCasing and the one we're currently using says `UniversalParcelId` vs. `UniversalParcelID` (which has roughly 15M downloads a week for the [deprecated version](https://www.npmjs.com/package/pascal-case) and ~7M for [the current one](https://www.npmjs.com/package/change-case)). Doesn't mean it's right, but points to some potential differences in implementations.

<img width="358" alt="image" src="https://github.com/user-attachments/assets/d51123f2-4beb-4652-9aa6-5e3df18852b0">

So, it seems reasonable to keep it like that until we do more research and figure out otherwise.

If there's no established specification for this outside of what Microsoft defines, which I'm not sure there is, then we shouldn't treat what they published as normative. 

However, this is a discussion that goes beyond this particular ticket and affects the entire DD. Probably better discussed elsewhere rather than here.
